### ISSUE TITLE
Persian (fa) Repo

### ISSUE THREAD

**Issue by 5y** [mozilla-l10n/appstores#60]
Hi, 
Why I can't find Persian (fa) repo in the list?

Thanks,
Reza

**Comment by flodolo** [comment]
Do Google Play and AppStore support Persian? That would be the main reason.

**Comment by TheoChevalier** [comment]
Google Play does support Persian https://l10n.mozilla-community.org/~pascalc/stores_l10n/api/google/storelocales/
App Store doesn’t https://l10n.mozilla-community.org/~pascalc/stores_l10n/api/apple/storelocales/

I’m checking if there is any other reason that would prevent us adding it to Google Play

**Comment by 5y** [comment]
@flodolo  Yes Google Play Does. 
@TheoChevalier  Thank you.

**Comment by flodolo** [comment]
I think that's because we're not currently shipping Fennec localized in Persian (at least not as part of the multilocale build). If I remember correctly there are pending issues with Fennec and RTL languages, but we could doublecheck with Jeff and Delphine in the next days.

**Comment by 5y** [comment]
Idkn exactly, but I thought RTL issues with Fennec resolved because i saw arabic in the list, Thank you for asking @flodolo

**Comment by TheoChevalier** [comment]
Arabic is here only as an experiment. I’m checking with Delphine.

**Comment by TheoChevalier** [comment]
Ok, Delphine told me that there is no RTL spec approved for iOS & Android yet, so that’s probably why we’re not distributing it through Google Play (as flod mentioned, fa is not part of the multilocales build, it’s only available here https://www.mozilla.org/en-US/firefox/android/all/?q=Persian )
So I think it would not make sense to translate Google Play in Persian since people can’t get the builds from there.

**Comment by 5y** [comment]
@TheoChevalier good, Thanks again.
